### ISSUE TITLE
How to take click event for image

### ISSUE THREAD

**Issue by VadivelChinnasamy** [1gravity/Android-RTEditor#102]
Hi,I used your project and i wanna try to take click event for image but not able to do it,Can please help me how to take click event for single and multiple image

**Comment by alanban** [comment]
http://stackoverflow.com/questions/5575438/how-to-add-click-action-for-the-imagespan

**Comment by 1gravity** [comment]
There's code to capture clicks for images on the barcode branch. Check out the RTEditorMovementMethod
