### ISSUE TITLE
The link of html code <a href="http://www.google.com"> not showing properly when I am loading the html content by using RTEditor.

### ISSUE THREAD

**Issue by richfuns** [1gravity/Android-RTEditor#104]
I just loaded below html content in RTEditor

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body><a href="http://www.google.com">google</a></body>
</html>
```

The link of a tag not working properly when I am loading the html content by using RTEditor. It just show like a plain text and not like a hyperlink.

Could anyone help me with this issue? 

Thanks in advance.

**Comment by 1gravity** [comment]
This is not a html editor, html is only used to persist the content of the rich text editor. Don't load arbitrary html into the editor and expect it to work.
