### ISSUE TITLE
Help with uploading image with rich text

### ISSUE THREAD

**Issue by anupkunwar123** [1gravity/Android-RTEditor#108]
If i include image in rich editor how can i send the whole rich text including image through an api to server. 
Thank you!

**Comment by thenewpotato** [comment]
I converted the content to HTML, parsed out the local path of the image, uploaded the image online, grabbed the URL, substituted the URL for the local path in the content HTML, then uploaded the content HTML to the server. I don't know if your server accepts HTML content or not though...

**Comment by 1gravity** [comment]
Please read this: https://github.com/1gravity/Android-RTEditor/blob/master/STORAGE.md. Implementing your own RTMediaFactory (or extending the default one) is the key to addressing this issue.
