### ISSUE TITLE
Image inserted won't generate <img .../> tag when getText(HTML)

### ISSUE THREAD

**Issue by qinjunli** [1gravity/Android-RTEditor#11]

**Comment by 1gravity** [comment]
Looks good to me:

<img src="/storage/emulated/0/Android/data/com.onegravity.rteditor.demo/files/images/1699231330_1434374587543.png"><img src="/storage/emulated/0/Android/data/com.onegravity.rteditor.demo/files/images/1856824631_1434374666566.png">

Please describe a test case that allows to reproduce an issue. A single liner in the subject isn't sufficient. I expect something along these lines (issues without that information will be closed without any further notice):

To expedite resolution of your issue, please provide as much relevant and
specific information as possible. This will probably require some work from
you. Most reports should include at least the following:

    * Which version of the SDK are you using?

    * Which Android build are you using? (e.g. MPZ44Q)

    * What device are you using?

    * What steps will reproduce the problem? (Please provide the minimal
reproducible test case.)

    * What is the expected output?

    * What do you see instead?

    * Relevant logcat output.

    * Optional: Link to any screenshot(s) that demonstrate the issue
(shared privately in Drive.)
    * Optional: Link to your APK (either downloadable in Drive or in the
Play Store.)
