### ISSUE TITLE
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.2

### ISSUE THREAD

**Issue by qa30m** [1gravity/Android-RTEditor#112]
My app's COMPILE SDK and MIN SDK are 26 and 16 and I use ANDROID SUPPORT REPOSITORY 26.0.0-alpha1. 
When I add this library it gives this error:
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.2

**Comment by 1gravity** [comment]
add google() to your project build file under repositories like:

```
repositories {
        jcenter()
        google()
```
