### ISSUE TITLE
How to show set and Show the richText on textview

### ISSUE THREAD

**Issue by asifmoin7766** [1gravity/Android-RTEditor#122]
Please tell me how can I set the rich text to a textview , by richtext I mean how to show the colorful text on the textview . Or can I get the html text created by richtext editor

**Comment by sureace** [comment]
I am also looking for the same requirement. It would be great if you provide view component like as RTEditText. I tried with TextView as you recommended in [https://github.com/1gravity/Android-RTEditor/issues/56](url) But it is not working as like as RTEditText component to render the HTML.

**Comment by sureace** [comment]
i have found html textview component [()](https://github.com/PrivacyApps/html-textview) which is working fine except it is not handling style attributes which are generated by RTEditText for html tags.

**Comment by 1gravity** [comment]
TextViews can render Spannable texts and EditText (RTEditText is an EditText) fields use Spannable internally so all you need to do it this: `textView.setText(editText.getText());`
