### ISSUE TITLE
Request: remove "android.support.v4.content.FileProvider" from manifest of the library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [1gravity/Android-RTEditor#138]
That's because apps can use it themselves.
It causes issues in this case, such as this one:
https://stackoverflow.com/questions/42893846/androidmanifest-merge-error-using-fileprovider

**Comment by 1gravity** [comment]
It's used for embedding pictures taken by the camera into the editor. If you don't need that functionality, you simply replace the whole node in your manifest: tools:node="replace"

You can also create a subclass for FileProvider as suggested in the SO question.

**Comment by AndroidDeveloperLB** [comment]
Is it really a "must" in the library?

**Comment by 1gravity** [comment]
No it's not but some ppl might want to use that. The build system allows you to remove whatever you want from the dependencies and the manifest so there's really no issue.

**Comment by AndroidDeveloperLB** [comment]
I think it should be a part of the demo, and not the library. The library doesn't really need this. It can ask for the needed functionality from outside of it.

**Comment by 1gravity** [comment]
Dependencies and configurations need to be defined where they are used and that's in the library project, I don't want to deal with things that should be encapsulated in a dependency (separation of concern). SDKs that ask me to add "stuff" to my project (like adding activity definitions in the manifest) don't understand how merging of projects work in Android. I only want to deal with dependency internals if there are conflicts (like in this case) and the Android build system offers me everything I need to solve these conflicts.

**Comment by AndroidDeveloperLB** [comment]
You wrote "It's used for embedding pictures taken by the camera into the editor." .
This is far from the purpose of a rich text editor.
For images, you can use a uri/url, that is provided by whoever uses the library.

**Comment by AndroidDeveloperLB** [comment]
I've now noticed that because this is set in the wrong place, it can cause build errors. Reported about this here:
https://github.com/1gravity/Android-RTEditor/issues/148
