### ISSUE TITLE
为啥如此设置字体恢复不了

### ISSUE THREAD

**Issue by Traveler1991** [1gravity/Android-RTEditor#162]
保存之前设置字体：
![QQ图片20200511144922](https://user-images.githubusercontent.com/13065967/81532408-e683db80-9396-11ea-93b4-4f6bb55e4a9c.png)
保存到数据库，再次打开，字体不恢复：
![QQ图片20200511144926](https://user-images.githubusercontent.com/13065967/81532440-f4396100-9396-11ea-9826-61bc2f437e1b.png)

**Comment by Traveler1991** [comment]
使用的方法是setRichTextEditing(true, content)

**Comment by 1gravity** [comment]
sorry I don't speak Chinese
