### ISSUE TITLE
Heading1 and heading2 formatting required

### ISSUE THREAD

**Issue by geeta4** [1gravity/Android-RTEditor#166]
Heading 1 and heading2 formatting required

**Comment by 1gravity** [comment]
This is not an HTML editor. If you want headers you can them by adding custom buttons that would set the formatting to a predefined size.

**Comment by 1gravity** [comment]
@geeta4 from your thumbs down I assume you expect others to do the work for you, for free of course. Maybe you haven't understood the concept of open source yet.
