### ISSUE TITLE
It's possible to create multiple rich text in a list view?

### ISSUE THREAD

**Issue by Matt237** [1gravity/Android-RTEditor#17]
I'm trying to create 5 rich texts on a listView but how can i manage the each row? e.g when i upload image from the gallery or when i scrolling the list and i want the data will be change? it's possible?

**Comment by 1gravity** [comment]
1. This is not a help forum but an issue tracker
2. If you are familiar with StackOverflow (that's where you could post your question) then you should know that there's no way to answer your question. It's pretty unclear what you're trying to achieve. Of course you can have a rich text editor field in a list view but "how can i manage each row" isn't a question with an answer. Neither is "It's possible" (what's possible?).

**Comment by Matt237** [comment]
Sorry but my english bad. I preferred to ask you beacuse you create this
rich text and you can help me. I need rich text for my school project.
Pleaseeee help me
בתאריך 10 ביולי 2015 12:31,‏ "Emanuel Moecklin" <notifications@github.com>
כתב:

**Comment by Matt237** [comment]
public class CustomAdapter extends BaseAdapter {

    Activity mContext;
    ArrayList<HandlerRichText> list;


    public CustomAdapter(Activity mContext, ArrayList<HandlerRichText> list) {
        this.mContext = mContext;
        this.list = list;
    }



    @Override
    public int getCount() {
        return list.size();
    }

    @Override
    public Object getItem(int position) {
        return list.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override

    public View getView(final int position, View convertView,
ViewGroup parent) {

        ViewHolder holder = null;

        if(convertView == null) {

            //inflate
            holder = new ViewHolder();
            LayoutInflater inflater = mContext.getLayoutInflater();
            convertView = inflater.inflate(R.layout.message_richtext, null);
            convertView.setTag(holder);

            //Views
            holder.editText = (RTEditText)
convertView.findViewById(R.id.rtEditText_1);
            holder.toolbarContainer = (ViewGroup)
convertView.findViewById(R.id.rte_toolbar_container);
            holder.tool_bar = (HorizontalRTToolbar)
convertView.findViewById(R.id.rte_toolbar);

            //Mange
            holder.rtApi = new RTApi(mContext, new
RTProxyImpl(mContext), new RTMediaFactoryImpl(mContext, true));
            holder.mRTManager = new RTManager(holder.rtApi, null);

            //Register
            holder.mRTManager.registerToolbar(holder.toolbarContainer,
holder.tool_bar);
            holder.mRTManager.registerEditor(holder.editText, true);

            holder.editText.requestFocus();


            holder.editText.addTextChangedListener(new TextWatcher() {
                @Override
                public void beforeTextChanged(CharSequence s, int
start, int count, int after) {

                }

                @Override
                public void onTextChanged(CharSequence s, int start,
int before, int count) {
                    list.get(position).setMessage(s.toString());
                }

                @Override
                public void afterTextChanged(Editable s) {

                }
            });




        }else{
            holder = (ViewHolder) convertView.getTag();
        }

        holder.editText.setRichTextEditing(true,
list.get(position).getMessage());




        return convertView;
    }


    static class ViewHolder{
        RTApi rtApi;
        RTManager mRTManager;
        RTEditText editText;
        ViewGroup toolbarContainer;
        HorizontalRTToolbar tool_bar;
    }





}


2015-07-10 12:34 GMT+03:00 Matan MatanB <matanbibas@gmail.com>:

**Comment by Matt237** [comment]
why when i pick image from gallery the Edittext resize it? can i get the
image in a real size to the EditText?

2015-07-10 12:34 GMT+03:00 Matan MatanB <matanbibas@gmail.com>:
