### ISSUE TITLE
Insta bug 11.3.0 is not working after integrated rteditor:1.7.6"

### ISSUE THREAD

**Issue by Bhavya0183** [1gravity/Android-RTEditor#170]
Hi, 
I have integrated rteditor:1.7.6 in my project. After integrated the library I am unable to launch my app. It is showing blank screen.
When I disable  insta bug 11.3.0 then the app is working properly. There is some conflict with these 2 libraries. Please help me out

**Comment by 1gravity** [comment]
I just integrated Instabug into the RTEditor demo app and it worked perfectly. I'm using Instabug 11.5.1 and 1.7.7 of my library. Maybe try the latest versions

**Comment by 1gravity** [comment]
I assume that the issue can be closed since it's working for me and no feedback in the last 8 days.
