### ISSUE TITLE
Toolbar always show ?

### ISSUE THREAD

**Issue by amaydiam** [1gravity/Android-RTEditor#19]
how to make toolbar always show onFocus or Out Focus TextEditor?

**Comment by 1gravity** [comment]
use RTManager.setToolbarVisibility(ToolbarVisibility) to configure the visibility of the toolbars. AUTOMATIC will show/hide them automatically depending on whether a rich text editor component has focus or not. SHOW will keep them visible at all times. HIDE will hide them at all times.
