### ISSUE TITLE
Material Dialog duplicate entry

### ISSUE THREAD

**Issue by rajazeeshanahmed** [1gravity/Android-RTEditor#22]
I get this error when compile the project, I'm already using material dialog library and want to exclude the one which you are using in this project. Please guide how can i exclude while adding dependencies 

Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/afollestad/materialdialogs/BuildConfig.class

**Comment by rajazeeshanahmed** [comment]
I try to exclude the material dialog module like this while adding dependency to my project 

compile ('com.1gravity:android-rteditor:1.1.7'){
        exclude module: 'materialdialogs'
    }

but it does not work.,

**Comment by 1gravity** [comment]
The version you're using is depending on a custom version of materialdialogs:

<dependency>
<groupId>com.1gravity</groupId>
<artifactId>android-rteditor-materialdialog</artifactId>
<version>1.1.2</version>
<scope>compile</scope>
</dependency>

I'm not a Gradle expert but I'm fairly certain you can exclude this by using:
        exclude group: 'com.1gravity', module:'android-rteditor-materialdialog'

BTW I'm working on a version does uses the regular materialdialog version and not a custom one. It should be available today through Maven Central.

**Comment by 1gravity** [comment]
I just released the new version that uses the official MaterialDialog libary. You can either remove your dependency or exclude the one used in the rich text editor by adding:

    compile ('com.1gravity:android-rteditor:1.2.1') {
        exclude group: 'com.github.afollestad.material-dialogs', module:'core'
    }
