### ISSUE TITLE
Unable to change the Actionbar's Title and Home/Back arrow color

### ISSUE THREAD

**Issue by rajazeeshanahmed** [1gravity/Android-RTEditor#24]
I'm trying to change the title color in action using the style

<style name="ThemeLight" parent="@style/RTE_ThemeLight">
        <item name="colorPrimary">@color/actionbar_color</item>
        <item name="colorAccent">@color/actionbar_color</item>
        <item name="colorPrimaryDark">@color/actionbar_color</item>
        <item name="actionMenuTextColor">@color/white</item>
        <item name="titleTextStyle">@style/MyActionBarTitleText</item>
    </style>
    <style name="MyActionBarTitleText" parent="@style/TextAppearance.AppCompat.Widget.ActionBar.Title">
        <item name="android:textColor">@color/white</item>
    </style>

but it does not work for me. Please guide.

**Comment by 1gravity** [comment]
This is a general Android development question so please ask on Stackoverflow.
