### ISSUE TITLE
Gradle failed.

### ISSUE THREAD

**Issue by AbuMuddz** [1gravity/Android-RTEditor#27]
Hi! When i try to put your project in my dependenciesit get this error:

Error:Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.0
<a href="openFile:C:/Users/MUDDII/AndroidStudioProjects/TestText/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by 1gravity** [comment]
you didn't add the maven { url "https://jitpack.io" }. Please read the readme.

**Comment by AbuMuddz** [comment]
I did it too. But that still have problems

**Comment by 1gravity** [comment]
Then you have some error in your gradle setup. If you follow the instructions properly it will compile and run.

**Comment by OuTlAnDeR24** [comment]
@Muuddz Hey, Were you able to resolve this issue? If yes, how?

**Comment by 1gravity** [comment]
The material dialog library isn't even used any more so that error message can't occur at all.

**Comment by OuTlAnDeR24** [comment]
@1gravity I was still using the older version. Upgraded. Working now! 👍
