### ISSUE TITLE
Issue with applying different styles without spacing

### ISSUE THREAD

**Issue by Blade24** [1gravity/Android-RTEditor#29]
@1gravity 
Hello, I've faced with a problem if I start typing with default style, after that I select for example bold, and I will not do a space the bold style will not be applied, it will continue display default style and if I add a space and continue typing - the text will become bold. The same issue happens for all styles (bold, underline, etc...)

Thanks in advance, Roman.

**Comment by 1gravity** [comment]
This is the keyboard and its auto-correct / auto-predict interfering. I ran some tests with different keyboards:
* Switfkey: doesn't apply the style in the middle of a work, applies to whole word if the cursor is at the end of that word
* Fleksy: applies the style but to the whole word
* Swype: works as expected in the middle of a word but not at the end (formatting is ignored)
* Go Keyboard: works as expected when turning formatting on but ignores turning formatting off
* Standard Samsung Keyboard: works as expected except applies the formatting to the whole word if the cursor is at the end of a word

The gist is that all but Go Keyboard interfere on how formatting is applied. The problem with turning off the formatting is indeed a problem of the rich text editor and I just fixed that with a86033272d77a1af29bcda4ed3d5e4ecb2fb44d7 (although on branch refactoring_effect which isn't quite ready to be merged to the main branch).
