### ISSUE TITLE
Adding bullets in empty line doesn't work

### ISSUE THREAD

**Issue by jakubkrolewski** [1gravity/Android-RTEditor#3]
I want to start an unordered list (bullets), so:
1. I press the "bullet" button -> it changes its state to activated, but no bullet is drawn
2. I start typing -> there's still no bullet and the button changes its state to not activated
The only way to add a bullet is to create the line of text first and then apply a bullet to it.

If changing the behaviour is not easy/possible, there should be at least an opportunity to tell the user how to add a bullet, so e.g. when the "bullet" button is pressed and the cursor is on an empty line, the button shouldn't be activated, but instead the edit text should notify the client application about this situation. The client application can now e.g. display a tooltip informing a user about the procedure of inserting bullets.

**Comment by 1gravity** [comment]
It's indeed not a trivial change and you're welcome to try to fix this.

**Comment by 1gravity** [comment]
Fixed with 49d1d23d392912232bebdb0799b6752f9a787e75
