### ISSUE TITLE
Supporting RTL languages

### ISSUE THREAD

**Issue by HamzehSoboh** [1gravity/Android-RTEditor#30]
Thank you for your great efforts, this works perfectly on LTR languages.
But when we use RTL languages, the direction is reversed, the opposite of the alignment icons.
If you can please fix it.
Thanks.

**Comment by 1gravity** [comment]
With 75696ee09b41e23db744e420f1c0450dab0a94bd RTL languages are properly supported. I haven't created a Maven Central version yet so if you want to use it, you'd need to import the source code. A new Maven Central version will be released once the paragraph formatting refactoring is done (branch refactoring_effect).

**Comment by 1gravity** [comment]
The latest published version adds RTL support, 49d1d23d392912232bebdb0799b6752f9a787e75
