### ISSUE TITLE
Image loading error

### ISSUE THREAD

**Issue by mqburhan** [1gravity/Android-RTEditor#36]
Hello,

I am using RTEditor library in my Android App, but when I load an image from device gallery, I get the below error message. The same error is got, when I use the library Demo app.
Could you please help me, how to fix it. 

Best,

01-11 11:54:16.385: E/AndroidRuntime(27585): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=Intent { dat=content://media/external/images/media/25054 (has extras) }} to activity {com.mqb.pashtostanderdfonts/com.onegravity.rteditor.media.choose.MediaChooserActivity}: com.onegravity.rteditor.api.RTApi$IncorrectInitializationException: Create an RTApi object before calling RTApi.getApplicationContext()

**Comment by 1gravity** [comment]
92edc7b81f6e3d40e13aa7cb8996113ef36c3394 modifies the way selected pictures are inserted into the rich text. Can you please test the latest version 1.4.0 and let me know if that fixes your issue?

If not please ask your question as you would on Stackoverflow (including stack trace and according code ).

**Comment by mqburhan** [comment]
I tested the last version 1.4.0 but unfortunately it gives the same error.

java.lang.RuntimeException: Unable to resume activity {com.onegravity.rte.demo/com.onegravity.rteditor.media.choose.MediaChooserActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=Intent { dat=content://media/external/images/media/53086 (has extras) }} to activity {com.onegravity.rte.demo/com.onegravity.rteditor.media.choose.MediaChooserActivity}: com.onegravity.rteditor.api.RTApi$IncorrectInitializationException: Create an RTApi object before calling RTApi.getApplicationContext()

**Comment by 1gravity** [comment]
Full stack trace

> 03-04 11:33:44.605 26468 26468 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.onegravity.rteditor.demo/com.onegravity.rteditor.med
> ia.choose.MediaChooserActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=Intent { dat=content://
> pl.solidexplorer2.files/storage/emulated/0/Download/picture.png typ=image/png }} to activity {com.onegravity.rteditor.demo/com.onegravity.rteditor.media.choose.
> MediaChooserActivity}: com.onegravity.rteditor.api.RTApi$IncorrectInitializationException: Create an RTApi object before calling RTApi.getApplicationContext()
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 03-04 11:33:44.605 26468 26468 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by 1gravity** [comment]
84ff08df45ca1455803cca5a2fe0688bfbb078f4 should fix this.
