### ISSUE TITLE
Error using Fragments

### ISSUE THREAD

**Issue by arthursz** [1gravity/Android-RTEditor#37]
Hi, i am trying to use your editor inside a fragment, but whenever i change the screen orientation from landscape to portrait or vice versa, the application crashes with this error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.Activities.MainActivity}: java.lang.IllegalStateException: The RTMediaFactory is null. Please make sure to register the editor at the RTManager before using it.

This is my code: 
[FragmentRTEditor.txt](https://github.com/1gravity/Android-RTEditor/files/91848/FragmentRTEditor.txt)

Other problem is that, pick image and take pictures button are not working using the toolbar implementation that comes with the project. I have to add something else to work? Or i am doing something wrong? I added the gradle dependency and use this code that a already provided.

There is any way to add video in the editor?

Thanks!

**Comment by 1gravity** [comment]
Please provide a stack trace. Ask the question as if this was stackoverflow...

**Comment by arthursz** [comment]
Sorry and thanks for the help, your editor is the best. Here is the stack trace:

E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.ufcspa.unasus.appportfolio, PID: 28388
E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ufcspa.unasus.appportfolio/com.ufcspa.unasus.appportfolio.Activities.MainActivity}: java.lang.IllegalStateException: The RTMediaFactory is null. Please make sure to register the editor at the RTManager before using it.
E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
E/AndroidRuntime:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3928)
E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:147)
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5253)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)




E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: The RTMediaFactory is null. Please make sure to register the editor at the RTManager before using it.
E/AndroidRuntime:     at com.onegravity.rteditor.RTEditText.assertRegistration(RTEditText.java:403)
E/AndroidRuntime:     at com.onegravity.rteditor.RTEditText.setRichTextEditing(RTEditText.java:315)
E/AndroidRuntime:     at com.onegravity.rteditor.RTEditText.onRestoreInstanceState(RTEditText.java:535)
E/AndroidRuntime:     at android.view.View.dispatchRestoreInstanceState(View.java:13629)
E/AndroidRuntime:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
E/AndroidRuntime:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2893)
E/AndroidRuntime:     at android.view.View.restoreHierarchyState(View.java:13607)
E/AndroidRuntime:     at android.support.v4.app.Fragment.restoreViewState(Fragment.java:468)
E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2042)
E/AndroidRuntime:     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:5991)
E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376) 
E/AndroidRuntime:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3928) 
E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:147) 
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1287) 
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5253) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by arthursz** [comment]
The first problem was resolved =D
We put the editor registration inside onViewCreated, like this:

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        // register editor & set text
        rtEditText = (RTEditText) getView().findViewById(R.id.rtEditText);
        rtManager.registerEditor(rtEditText, true);
    }

But pick image and take picture still doesn't work.

**Comment by 1gravity** [comment]
I extended the demo app to show an Activity and a Fragment based implementation: 54a2efcbdf585cfdec27219cd3f7169a93906637.

The image issue is due to you not calling through to RTManager.onActivityResult.
When picking an image that happens in a separate Activity which reports back a reference to the image  to the rich text editor. Check out the new RTEditorActivityWithFragment to see what is needed in onActivityResult. I'm considering using EventBus to replace that communication and to make the onActivityResult "hack" obsolete.

**Comment by 1gravity** [comment]
I actually just replaced the tedious Intent/onActivityResult mechanism by a simple EventBus post. I haven't published version yet but will sometimes today.

**Comment by 1gravity** [comment]
Oh and next time create separate issues for each problem please.
