### ISSUE TITLE
Modify HTML tag

### ISSUE THREAD

**Issue by arthursz** [1gravity/Android-RTEditor#39]
Hey! I am trying to create a custom tag for my application. I want to create something like this: 
```javascript
<font id="1" style="background-color:#000000">Teste</font id="1">
```
add a identifier <b>id="1"</b> inside the HTML tag. But i can't understand how i can alter the tags in your code. Is there any way?

Thanks

**Comment by 1gravity** [comment]
Have a look at the ConverterSpannedToHtml class:
```
        } else if (style instanceof BackgroundColorSpan) {
            mOut.append("<font style=\"background-color:#");
            String color = Integer.toHexString(((BackgroundColorSpan) style).getBackgroundColor() + 0x01000000);
            while (color.length() < 6) {
                color = "0" + color;
            }
            mOut.append(color);
            mOut.append("\">");
```

Tip: use shift+ctrl+f to search for text in the project (assuming you're using Android Studio).

**Comment by arthursz** [comment]
Thanks!!!!!!!!!!!!!!!!!!!!! It's exactly what i needed =D
