### ISSUE TITLE
get selected text in HTML format

### ISSUE THREAD

**Issue by icaromsc** [1gravity/Android-RTEditor#40]
Hey! I'm trying to get selected text from the Editor but i'm just getting the select text without HTML format.
This is the code:
`startSelection = mRTMessageField.getSelectionStart();
                    endSelection = mRTMessageField.getSelectionEnd();
                    String selectedText = mRTMessageField.getText(RTFormat.HTML).substring(startSelection, endSelection);`

 When i try to create a new string parsing the html string with the select text i'm getting the position without html and the selected text is not completed because the position of plain text is different in html format.

This is my logcat when I've selected the text "My first Text!":

 >```01-28 13:36:41.555 18456-18456/com.ufcspa.unasus.appportfolio D/Processing text:: finding selected text:<b>my</b> firs
                                                                                   in text:This is <b>my</b> first <b>Text</b>!
01-28 13:36:41.557 18456-18456/com.ufcspa.unasus.appportfolio D/Processing text:: selected text starts at position '8' ends at position '22'
01-28 13:36:41.557 18456-18456/com.ufcspa.unasus.appportfolio D/Processing text:: substring generated:<b>my</b> firs ```

The selected text have 14 characters "My first Text!" but the string selected was ```"<b>my</b> firs" ```

Is there any way to get the selected text in HTML form?

Thanks!

**Comment by 1gravity** [comment]
You need to retrieve the selected text as a Spanned text and the convert it to HTML. The getSelectionStart() and getSelectionEnd() indicate the selection in the text as you see it in the editor and that's in Spanned format not in HTML.

So something like this:
```
int selStart = mRTMessageField.getSelectionStart();
int selEnd = mRTMessageField.getSelectionEnd();
Spannable text = (Spannable) mRTMessageField.getText().subSequence(selStart, selEnd);
RTHtml<RTImage, RTAudio, RTVideo> rtHtml = new ConverterSpannedToHtml().convert(text, RTFormat.HTML);
String thatsMySelectionInHTML = rtHtml.getText()
```

**Comment by 1gravity** [comment]
You're welcome by the way...
