### ISSUE TITLE
BR Tag

### ISSUE THREAD

**Issue by arthursz** [1gravity/Android-RTEditor#41]
Hey! Man, i noticed that when you have a background color tag and you press enter to create another line (a br tag is inserted) the background color tag is duplicated like this:

```
<font id='1' style="background-color:#70e7d0">Test 1<br/>
<id='1' /font><font id='1' style="background-color:#70e7d0">Test 2<id='1' /font>
```

Why this happens? Why it can't be like this:

```
<font id='1' style="background-color:#70e7d0">Test 1<br/>Test 2<id='1' /font>
```

Thanks!

**Comment by 1gravity** [comment]
Feel free to submit a pull request
