### ISSUE TITLE
problem with setRichTextEditing

### ISSUE THREAD

**Issue by maysamrasoli** [1gravity/Android-RTEditor#42]
hi
when i use "setRichTextEditing"  in programming side , dont  implementation conditions like "Bold" , "italics".

how i fix this problem??

**Comment by 1gravity** [comment]
Ask your question like you would on Stackoverflow: http://stackoverflow.com/help/how-to-ask. There's no way to understand what you mean with your question above. What do you do, what do you expect to happen, what happens, show code.

**Comment by maysamrasoli** [comment]
thank you for answer.
let me explain more,
for example user set bold true in toolbar in editor,
and i want to add a special string with this code  "RTEditText.setRichTextEditing(true, "My content");"
when the string added to RTEditText , it is not bold !!!
how to add  to the string, all conditions that user is selected??

**Comment by maysamrasoli** [comment]
i find my answer,
i use this code:

>   Selection selection = new Selection(edtContent);
            str.insert(selection.start(), newString);

and worded.
thank you so much.
