### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by mojojo098** [1gravity/Android-RTEditor#44]
an app im making uses appcompat support lib v19
but when i put Android-RTEditor in my dependencies my custom theme disappear... before it only disappears when i use appcompatsupport libv21 and up... could you explain why this happen when im just putting the dependency..

**Comment by 1gravity** [comment]
The rich text editor uses the MateralDialog library which in turn uses appcompat-v7:23.2.0. If you have a custom theme you need to either extend the RTEditor themes or define all custom attributes the rich text editor uses in your own theme. There is no need to add the com.android.support:appcompat-v7 library in your own build file.
