### ISSUE TITLE
Update gradle version with latest code fixes for support library

### ISSUE THREAD

**Issue by fmnstr** [1gravity/Android-RTEditor#48]
Please, update gradle version with the latest commits for EventBus 3.0.0 and material dialogs v.0.8.5.5 that resolves an issue with the latest support library.

**Comment by 1gravity** [comment]
c56567bc9a31d57031ad3b5fd452ca87b512b784 fixed this 4 days ago.
ebc97f2dae8f5138415105f6c55f8f49e61ac6f7 brings a new version that you can include with
`compile 'com.1gravity:android-rteditor:1.4.1'`

**Comment by fmnstr** [comment]
Thank you!!
