### ISSUE TITLE
set cursor to end of text, setSelection(position);not working

### ISSUE THREAD

**Issue by zniter81** [1gravity/Android-RTEditor#49]
Hi,

the setSelection(int) does not work.
my cursor still at the starting position.

this is my code.
mRTMessageField.setRichTextEditing(true, content); 
mRTMessageField.setSelection(content.length()); 

can advice?

**Comment by 1gravity** [comment]
If I add this to the demo app, it works perfectly:

        String content = "Hello World";
        mRTMessageField.requestFocus();
        mRTMessageField.setRichTextEditing(true, content);
        mRTMessageField.setSelection(content.length());

You'd have to provide more details on what you're doing

**Comment by zniter81** [comment]
Hi 1gravity,

i followed the above code. And the setSelection(position) cursor works.
initially it not working because my content is HTML.

```
String content = "<b><u>" + pr.Subject + "</u></b><br/>";
mRTMessageField.setRichTextEditing(true, content);
mRTMessageField.setSelection(mRTMessageField.getText(RTFormat.SPANNED).length());
```
