### ISSUE TITLE
Cursor takes height same as selected image height

### ISSUE THREAD

**Issue by arvindkumar98** [1gravity/Android-RTEditor#50]
I am using this lib in my own project but getting an issue. When I select image then cursor size increase as image size. I tried very often but not got any 
![screenshot from 2016-04-21 17 33 09](https://cloud.githubusercontent.com/assets/9417813/14708309/ac2fc726-07e7-11e6-9d5e-bf9ca5d7b678.png)
solution please tell me how can i fix this problem.

With Regards
Arvind Kumar

**Comment by 1gravity** [comment]
There's nothing to fix, that's how Android handles it, works as designed.
