### ISSUE TITLE
<Strike> Bug

### ISSUE THREAD

**Issue by diegomontoya** [1gravity/Android-RTEditor#54]
To reproduce

1) Load/Set the following html to editor

```html
<strike>testing abc</strike>
```

```java
 mRteEditText.setRichTextEditing(true, "<strike>testing abc</strike>");
```

2) The editor is unable to enable the Strike toolbar button select state even though it is properly parsed into spans. Output of the editor is also correct so the strike span is there but the RTManager.java effect.existsInSelection(editor) is evaluating to false for some reason.

**Comment by 1gravity** [comment]
Thanks for reporting this. It didn't just affect the strikethrough but other effects too (big, small, subscript, superscript etc.).

Fixed with 65322d5a2564516318df2c161313444d2d382a64
