### ISSUE TITLE
How to show text returned by rich text editor?

### ISSUE THREAD

**Issue by sacOO7** [1gravity/Android-RTEditor#56]
The text is returned in format  " Rtformat.HTML ". If possible to show in textview , how should I show it?

**Comment by 1gravity** [comment]
Why would you retrieve it from a TextView as HTML and then show the same text in a TextView again? If you really want to show it in another TextView retrieve is as Spanned text.

**Comment by sacOO7** [comment]
There's little confusion. I'm talking about text returned from RTEditText and then showing it in proper way.I was just wandering if there is any widget available that can show this text properly?

**Comment by 1gravity** [comment]
There's no confustion, at least not on my side ;-).
The rich text editor is an EditText and therefore also a TextView. Whatever is shown in the editor can also be shown in a TextView without any changes. The format a TextView/EditText uses is Spanned text. You might want to read up on the Spanned class.

**Comment by sacOO7** [comment]
Okk sorry for that . Little confused. TextView is parent class of Edittext. So simple settext method on textview will render HTML text properly? Thats what I was trying to ask.:P
