### ISSUE TITLE
Problem while displaying floating toolbar

### ISSUE THREAD

**Issue by sacOO7** [1gravity/Android-RTEditor#59]
Hi I'm getting problem while showing floating toolbar when keyboard shows up? Can you tell me the cause of that?It will be really helpful if you can provide me with some details.

**Comment by 1gravity** [comment]
"Getting problem...". You guys need to learn how to ask a good question: http://stackoverflow.com/help/how-to-ask. I'm willing to help but I'm not a support center.

**Comment by sacOO7** [comment]
Sorry for asking "Getting problem...." , Btw I have found out the solution , thanks to ur late reply :)
