### ISSUE TITLE
Theme rte_toolbar_themes.xml copied to current theme but still app crashing

### ISSUE THREAD

**Issue by kumarbhubnesh** [1gravity/Android-RTEditor#61]
Hi, I need my current theme for that as written in the help that we can copy all the attributes from rte_toolbar_themes.xml to my own theme, I have copied the theme items to my theme but its not picking it up and app is crashing. After applying the theme told in readme my action bar is not visible.

**Comment by 1gravity** [comment]
Please create issues that live up to SO standards: http://stackoverflow.com/help/how-to-ask.
There's no way to answer your question with that little information. No posted code, no stacktrace (app crashing...).
