### ISSUE TITLE
Custom Button

### ISSUE THREAD

**Issue by long1EU** [1gravity/Android-RTEditor#68]
Is it possible to add a custom button that changes the background to a specific color? Say I want to make text background red with one button and black with another.

**Comment by 1gravity** [comment]
Everything is possible ;-).
Just add the buttons to the toolbar layout and deal with the click in the HorizontalRTToolbar.onClick() method.  The mBGColorListener shows you how to apply to color to the text.

**Comment by long1EU** [comment]
Thank you so much. 
Can I Override that method?
Is this the imprementation of the color?
mListener.onEffectSelected(Effects.BGCOLOR, color);

**Comment by long1EU** [comment]
HorizontalRTToolbar.mListener.onEffectSelected(Effects.BGCOLOR, 0x990000);
 
mListener is marked as private

**Comment by 1gravity** [comment]
You need to use the library by adding the source code to your project to be able to make that change

**Comment by long1EU** [comment]
just did that, I thought that there is a easy way. thank you so much for your work
