### ISSUE TITLE
Not load html content

### ISSUE THREAD

**Issue by nachiketghelani** [1gravity/Android-RTEditor#69]
When it save file to storage after that we load that html file to editor so we get only text. can we get custom html portion like (         mOut.append("<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td>
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td>
    <td>94</td>
  </tr>
  <tr>
    <td>John</td>
    <td>Doe</td>
    <td>80</td>
  </tr>
</table>");
            mOut.append("<br/>");)

please give me some information about how to i add custom html content.

**Comment by 1gravity** [comment]
The html is just an export format to persist whatever is in the rich text editor. It's not an html editor. If you want to be able to edit tables, you'd have to implement it on editor side.
