### ISSUE TITLE
Push my own images

### ISSUE THREAD

**Issue by long1EU** [1gravity/Android-RTEditor#70]
I want to add barcode images automatically but this implementation doesn't work, is there a way around it?

`public class CustomRTManager extends RTManager {
    String path;
    Bitmap barcode;
    int width, height;

    public CustomRTManager(RTApi rtApi, Bundle savedInstanceState) {
        super(rtApi, savedInstanceState);
    }

    public void setImageForBarcode(Bitmap barcode, String path, int width, int height) {
        this.path = path;
        this.width = width;
        this.height = height;
        this.barcode = barcode;
        setImage();
    }

    public void setImage() {
        RTMedia media = new RTImage() {
            @Override
            public String getFilePath(RTFormat format) {
                return path;
            }

            @Override
            public String getFileName() {
                return path.substring(path.lastIndexOf("/"));
            }

            @Override
            public String getFileExtension() {
                return path.substring(path.lastIndexOf("."));
            }

            @Override
            public boolean exists() {
                return new File(path).exists();
            }

            @Override
            public void remove() {
                new File(path).delete();
            }

            @Override
            public int getWidth() {
                return width;
            }

            @Override
            public int getHeight() {
                return height;
            }

            @Override
            public long getSize() {
                return barcode.getByteCount();
            }
        };
        MediaEvent barcode = new MediaEvent(media);

        if (barcode.getMedia().exists()) {
            Log.d("test", "mediaaa");
        }
        onEventMainThread(barcode);
    }
}`

**Comment by 1gravity** [comment]
There's a new branch "barcode". Let's discuss this "there".
