### ISSUE TITLE
Disable loading fonts

### ISSUE THREAD

**Issue by Remie-l** [1gravity/Android-RTEditor#76]
Is there a way to disable font loading? I use custom toolbar and removed button Fonts from there, but looks like fons still loading at start.

**Comment by 1gravity** [comment]
It's loading the fonts in the HorizontalRTToolbar.getFontItems. You can just remove the initialization of the font adapter in line 173:
```
mFontAdapter = createDropDownNav(mFont,
                R.layout.rte_toolbar_font_spinner,
                R.layout.rte_toolbar_spinner_item,
                getFontItems(), mFontListener);
```
