### ISSUE TITLE
Image url

### ISSUE THREAD

**Issue by Remie-l** [1gravity/Android-RTEditor#77]
Can you please tell, in which way i can change function of Image button to make it insert html image URL, like Link button? Or, maybe there is a simple way to create custom buttons?

**Comment by 1gravity** [comment]
We'll I'm not going to walk you through this. I'm willing to answer questions that have Stackoverflow quality meaning concrete programming questions not broad inquires like this one. At least you should try something yourself before asking questions here. This is btw an issue tracker not a q&a forum.
