### ISSUE TITLE
How to disable loading system fonts / Show only the indexed fonts in the list

### ISSUE THREAD

**Issue by mori-honest** [1gravity/Android-RTEditor#84]
I have a dedicated folder for RTfonts and other folders for other fonts of app which i don't want to include in the drop down. Also system fonts are loading in the list which is not what i want.How can i config library to load only the fonts in special folder in assets?

**Comment by 1gravity** [comment]
You can't configure it but you can disable the loading of the system fonts in the com.onegravity.rteditor.fonts.FontManager.getSystemFonts() -> simply remove the method code (leave the method signature).

**Comment by long1EU** [comment]
You need even to learn more or to hire someone to do your work.

**Comment by mori-honest** [comment]
@1gravity Thanks for your help!
I really appreciate it.

@long1EU That words hurt me man! 
we are learning everyday to do work and there is no point in our path which we could say I AM PERFECT AND KNOW EVERYTHING! There is always something to learn.
To learn more, when there is no one around to ask, the best solution i found was to just ask!
Thank you anyway.

**Comment by long1EU** [comment]
man, I had no one to ask, I just read and read the code and try to make sense. You need to get up on your feet you can't just ask someone to solve your problem, but instead you need to do something about it an try util it work, you won't get long la as a developer like that. Yesterday I was willing to look at your code but you didn't want. Sorry for been so direct, but no one helped me, all I learned is from what I done myself.

**Comment by mori-honest** [comment]
I am alone in Android development too and do a lot of mess to learn but asking the library developer to help will make it easier to understand the logic for us as library users and maybe help developer to think of new features or finding bugs.

> Yesterday I was willing to look at your code but you didn't want.

I understood now what you were saying then about "teamview" = Team viewer. I thought you mean some tool which i don't have. my bad. sorry!
