### ISSUE TITLE
No resource found that matches the given name '....‘

### ISSUE THREAD

**Issue by pangxinlong** [1gravity/Android-RTEditor#85]
Main gradle config:
android {
    compileSdkVersion 17
    buildToolsVersion "23.0.2"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 23
    }

RETditor project is lib
lib Grade config:
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.1gravity:android-rteditor:1.6.2'
    compile 'com.1gravity:android-colorpicker:2.0.2'
    compile 'com.zzhoujay.richtext:richtext:2.0.13'
}

I Bluid Error:
/Users/password/AndroidStudioProjects/ZXStock/richeditor/build/intermediates/res/merged/debug/values-ldltr-v21/values-ldltr-v21.xml
 Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.

/Users/password/AndroidStudioProjects/ZXStock/richeditor/build/intermediates/res/merged/debug/values-v21/values-v21.xml
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Inverse'.
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large.Inverse'.
 Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium.Inverse'.
Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar'.
....

**Comment by 1gravity** [comment]
use the latest build tools (24.0.3) and compile with API level 23 instead of 17 and try again.

**Comment by pangxinlong** [comment]
OK，Thank you！

**Comment by 1gravity** [comment]
If that solved the issue can you please close it?
