### ISSUE TITLE
Warning:Module 'com.android.support:appcompat-v7:24.0.0' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by SanjayAndroidDev** [1gravity/Android-RTEditor#86]
I got this error at build time.

Error:A problem occurred configuring project ':app'.
> Could not find appcompat-v7.jar (com.android.support:appcompat-v7:24.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/appcompat-v7/24.0.0/appcompat-v7-24.0.0.jar

My build.gradle file like this

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "24.0.3"

    defaultConfig {
        applicationId "com.oneclick.advisortlc"
        minSdkVersion 17
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    repositories {
        maven { url "https://jitpack.io" }
        maven {
            name 'maven.aviary.com'
            url uri("http://maven.aviary.com/repo/release")
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:cardview-v7:23.3.+'
    compile 'com.android.support:design:23.3.0'
    compile 'com.intuit.sdp:sdp-android:1.0.3'
    compile project(':SlidingMenu')
    // retrofit, gson
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.squareup.retrofit2:retrofit:2.0.1'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.2.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.yqritc:recyclerview-flexibledivider:1.4.0'
    compile 'com.aviary.android.feather.sdk:aviary-sdk:3.6.3'
    compile 'com.github.QuadFlask:colorpicker:0.0.12'
    compile project(':libraryNew')
    //    compile files('libs/android-feather-library.jar')
    compile files('libs/aspectjrt-1.7.3 (1).jar')
    compile files('libs/isoparser-1.0.6.jar')
    compile files('libs/commons-logging-1.1.2.jar')
    compile project(':MaterialSearchview')
    compile 'com.github.PhilJay:MPAndroidChart:v2.1.6'
//    compile 'jp.wasabeef:richeditor-android:1.2.1'
//    compile project(':RTEditor-Toolbar')
    compile 'com.1gravity:android-rteditor:1.6.2'
}

**Comment by 1gravity** [comment]
That build file will inevitably cause issues. You're mixing different versions of the same library. appcompat:23.4.0, design:23:3.0 etc. Some of the linked libraries use their own version of appcompat and other support libraries. I'd recommend to use the latest ones only (24:2:1) and make sure to use the same version for all support libraries. Also make sure you have jcenter() as repository in your app build file.

This also has nothing to do with this library. Please ask these questions on Stackoverflow ;-).
