### ISSUE TITLE
High density toolbar drawable resources missing

### ISSUE THREAD

**Issue by vit001** [1gravity/Android-RTEditor#88]
In Android-RTEditor-master\RTEditor-Toolbar\src\main\res\ the are only drawable resources from ldpi to xhdpi. xhdpi looks terrible and blurry on a xxxhdpi screen. Can you pls add xxxhdpi resources?

**Comment by 1gravity** [comment]
You are aware that this is an open source library and you can easily submit a pull request to provide the resources YOU want, right?

**Comment by vit001** [comment]
I do not have the svg files from which the resources were created, nor are they part of the project. It is simple to do for whoever has them.

**Comment by 1gravity** [comment]
Except there are no svg files

**Comment by vit001** [comment]
Where did the resources come from?

**Comment by 1gravity** [comment]
they were created by a Polish graphic designer and he didn't create svg, now stop wasting mine or your time

**Comment by vit001** [comment]
If anyone is wasting someone's time it's you. It is almost 2017 with the majority of devices running xxhdpi and xxxhdpi, making this library unusable. Yet for some reason you insist on being unhelpful in remedying this.

**Comment by 1gravity** [comment]
lol, what an arrogant idiot, asking others to do your fucking work, get your finger out of your ass and do it yourself

**Comment by 1gravity** [comment]
I can see from your "contributions" (there are none) that you're one of those damn leeches you only take from others and never give anything back, go back to your fucking cave you came from

**Comment by vit001** [comment]
Dude you clearly hate this project, why don't just take it off github, and find something else to do with your life that won't irritate you so much? Just sayin.

**Comment by 1gravity** [comment]
I don't hate the project but people like you who think they can ask others to do their work for them without moving a finger themselves. You are aware that I paid the Polish graphic designer a 4 digit amount of $ for the resources but I still released it as open source? How about you hire someone to do the work for you?

**Comment by vit001** [comment]
Dude now I just have to feel sorry for you.

**Comment by 1gravity** [comment]
That remark is fitting... Nothing to contribute but a big mouth

**Comment by vit001** [comment]
Just this project down before you get a stroke. Seriously.

**Comment by 1gravity** [comment]
Just this project down..., illiterate too is he the little leech
