### ISSUE TITLE
Err: Resource is not a Drawable

### ISSUE THREAD

**Issue by amberbhargava** [1gravity/Android-RTEditor#9]
Thanks a lot for sharing this code!  

I am getting this error when I am inflating the layout with the toolbar in the onCreateView method of the fragment. 

Binary XML file line #33: Error inflating class com.onegravity.rteditor.toolbar.RTToolbarImageButton
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f0100f3 a=-1}

Not sure if I am doing something wrong or its an issue with the code.

**Comment by 1gravity** [comment]
Probably an issue with the build, usually building it from scratch helps. It's certainly not a code issue or it wouldn't work at all.

**Comment by agungsijawir** [comment]
You need to be carefully when setup on onCreate(). I experienced this error, but when I reading the example, I know my error.

```java
    protected void onCreate(Bundle savedInstanceState) {
        String initialMessage = null;

        if (savedInstanceState == null) {
            Intent intent = getIntent();
            initialMessage = getStringExtra(intent, "initialMessage");
        } else {
            initialMessage = savedInstanceState.getString("initialMessage", "Hello, <b>this</b> is a sample message!");
        }

        // you need to initial theme
        setTheme(R.style.ThemeLight);

        // then do this
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // after that, do exactly as demo says
        RTApi rtApi = new RTApi(this, new RTProxyImpl(this), new RTMediaFactoryImpl(this, true));
        rtManager = new RTManager(rtApi, savedInstanceState);

        // define and register toolbar to manager 
        // define and register editor to manager 
        // set initial message 
    }

```

**Comment by 1gravity** [comment]
setTheme needs to be called before setContentView  as stated here: http://developer.android.com/reference/android/view/ContextThemeWrapper.html#setTheme(int)

**Comment by cristenicu** [comment]
`setTheme(R.style.ThemeLight);` give me this error `cannot find symbol variable ThemeLight`

**Comment by 1gravity** [comment]
@cristenicu you didn't define the ThemeLight in your application (theme.xml or style.xml or whatever you call it). Please check out the demo app code.
