### ISSUE TITLE
Not Saved in Richtext Editor

### ISSUE THREAD

**Issue by rajeshlawrance** [1gravity/Android-RTEditor#91]
Hi

 Here If i save the rich text file. The following error occurs. Kindly need help for this issue.

Failed to ensure directory: /storage/sdcard1/Android/data/com.onegravity.rteditor.demo/files

**Comment by long1EU** [comment]
Hi, 
Please answer the flowing questions :

1. Which version of the SDK are you using?Android build are you using? (e.g. MPZ44Q)
2. What device are you using?
3. What steps will reproduce the problem? (Please provide the minimal reproducible test case.)
4. What is the expected output?
5. What do you see instead?
6. Relevant logcat output.
7. Optional: Link to any screenshot(s) that demonstrate the issue (shared privately in Drive.)
8. Optional: Link to your APK (either downloadable in Drive or in the Play Store.)

**Comment by rajeshlawrance** [comment]
1. I am using SDK version 4.4.4 ( KITKAT  version)
![device-2016-11-04-120344](https://cloud.githubusercontent.com/assets/5163495/19996609/c8d85b10-a286-11e6-8e3f-1e3e9487e8fb.png)

2. I am using MI Pad tablet 7.8 inches.

3. I got the following line in my LOGCAT If i click the save button in Action Bar

.

11-04 12:04:21.498 10787-10787/com.onegravity.rteditor.demo W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.onegravity.rteditor.demo/files

**Comment by 1gravity** [comment]
There's something wrong with the app's permissions. This should only happen if the app has no permissions to create the directory structure

**Comment by rajeshlawrance** [comment]
ok thanks.

On Thu, Nov 10, 2016 at 10:57 PM, Emanuel Moecklin <notifications@github.com
