### ISSUE TITLE
Display an image using remote URL in editor ?

### ISSUE THREAD

**Issue by sjunaidkhaan** [1gravity/Android-RTEditor#94]
Hello 1Gravity, 

Thanks for such a wonderful lib, can I ask a simple question, I reviewed the issue thread and the query that I have was not answered, though the same issue was reported in nov 2015, I am asking it again any possibility that we can load an image through a remote url like http://ww.abc.com/xyz.jpg in the img tag ? It's not working at the moment.

best regards
Junaid

**Comment by 1gravity** [comment]
You have three options if you want this:
1. You can wait for "someone" to implement it (not gonna be me)
2. You can submit a pull request
3. You can hire someone to implement it for you 
There's no point in posting the same issue twice though, so I'm going to close this one.

**Comment by sjunaidkhaan** [comment]
Well Emanuel, thanks for such a rigid response, I have no issues to do it myself or hire that "someone", because I was curious that 1 year has passed so you might have had it done. So, there is no point in mentioning 1-3, and sorry if you felt offended by re-posting it as an year has passed since it was posted here. 

thanks anyway for a good lib.

**Comment by 1gravity** [comment]
If someone had done it, the issue would be closed now wouldn't it?

**Comment by sjunaidkhaan** [comment]
It was never tapped again.
