### ISSUE TITLE
Re-arrange buttons layout

### ISSUE THREAD

**Issue by tvstuff** [1gravity/Android-RTEditor#97]
Hi,
Is there any possible option/feature to remove some buttons from bottom layout OR
is there any way to re-arrange feature buttons layout positions? because user need right scroll to see other options, i want to make layout to display all the buttons.

Thanks in advance.

**Comment by thelong1EU** [comment]
Can you provide an image of what you are requesting?

**Comment by 1gravity** [comment]
You can create whatever layout you want and use that instead of the default one(s). The demo app includes even two different layouts for the toolbar, feel free to create your own one.

**Comment by tvstuff** [comment]
Thank you.
