### ISSUE TITLE
Problem with .getText()

### ISSUE THREAD

**Issue by nartalex** [1gravity/Android-RTEditor#98]
Hello,

I've added TextChangedListener and try to get text from EditText.
When I type something, it changes in strange way.
The problem happens on virtual devices with SDK 22 and 23.
For example, on that screenshot I've tried to type "qwerty"
![image](https://cloud.githubusercontent.com/assets/26258767/24073150/ee9797f8-0c03-11e7-8bfd-d14d13773d69.png)

This is my onCreate method:

        RTApi rtApi = new RTApi(this, new RTProxyImpl(this), new RTMediaFactoryImpl(this, true));
        RTManager rtManager = new RTManager(rtApi, savedInstanceState);

        final RTEditText rtEditText = (RTEditText) findViewById(R.id.rtEditText);
        rtManager.registerEditor(rtEditText, true);

        rtEditText.addTextChangedListener(new TextWatcher() {
            boolean changed = false;

            @Override
            public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {
            }

            @Override
            public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
            }

            @Override
            public void afterTextChanged(Editable editable) {
                String text = rtEditText.getText(RTFormat.HTML);
            }
        });

**Comment by 1gravity** [comment]
I added your TextWatcher in the demo app but without any issues. Likely an emulator problem but I'm not going to fix issues caused by emulators, unless you tell me it's reproducible on a real device?

**Comment by Kaustubh-Deshmukh** [comment]
I am also facing the same issue on a real device. If you type or delete text pretty fast (mostly), then the edit text duplicates the text and appends.
For example if I am typing "Qwerty" while typing suppose, I reach letter 'r', then instead of showing "Qwer", it shows, "QweQwer".

Same happens with delete. The text gets appended.
